# -*- coding: utf-8 -*-
"""webscraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10H3tZL47_jK_8vmL1tYTmI7Zuz1FFDk6
"""

from google.colab import drive
from bs4 import BeautifulSoup
import requests
import csv

#URL ONDE ESTA A LISTA DE EMAIL A SEREM EXTRAIDOS
link = 'https://vinirodrigues.github.io/raspagem-emails/'
requisicao = requests.get(link)
#DEVE RETORNAR 200 PARA REQUISÇÃO FUNCIONAR
print(requisicao)
site = BeautifulSoup(requisicao.text, "html.parser")
#INDENTA O HTML PARA MELHOR ANALISE
print(site.prettify())

#LOCALIZA A LISTA PELA TAG
lista = site.find("ul")
print(lista)

#MONTA O GOOGLE DRIVE
drive.mount('/content/drive')

# Supondo que a variável 'lista' já contenha a tag <ul> com os itens
# Vamos analisar a variável 'lista' usando BeautifulSoup
soup = BeautifulSoup(str(lista), 'lxml')

# Extraia os itens da lista <li>
items = [li.text for li in soup.find_all('li')]

# Verifique os itens extraídos
print(items)

# Nome do arquivo CSV a ser criado
csv_file_path = '/content/drive/My Drive/lista.csv'

# Escreva os itens em um arquivo CSV
with open(csv_file_path, 'w', newline='', encoding='utf-8') as csvfile:
    csvwriter = csv.writer(csvfile)

    # Escreva o cabeçalho (opcional)
    csvwriter.writerow(['Item'])

    # Escreva os itens da lista
    for item in items:
        csvwriter.writerow([item])

print(f"Arquivo CSV criado com sucesso em: {csv_file_path}")

